### ISSUE TITLE
Update dependecy RestSharp

### ISSUE THREAD

**Issue by racingsoft** [asherber/MailmanSharp#1]
It is possibe update RestSharp to version 106.10.1?

**Comment by asherber** [comment]
I'll take a look. RestSharp does tend to introduce little breaking changes with each major version, which means that dependent libraries need to retest before allowing a new version to be used.

**Comment by racingsoft** [comment]
I cloned the repository and updated the dependency with no problems. One method is deprecated, but still working.

**Comment by asherber** [comment]
I just looked at the library. MailmanSharp currently asks for RestSharp >= 106.2.1 and < 107. You should be able to use 106.10.1 just by adding a dependency in your application.

So if your project file currently has:
```xml
  <ItemGroup>
    <PackageReference Include="MailmanSharp" Version="3.0.4" />
  </ItemGroup>
```
All you have to do is change it to:

```xml
  <ItemGroup>
    <PackageReference Include="MailmanSharp" Version="3.0.4" />
    <PackageReference Include="RestSharp" Version="106.10.1" />
  </ItemGroup>
```
MailmanSharp will then use the same version of RestSharp that your project specifies.

**Comment by racingsoft** [comment]
Thanks!
